### ISSUE TITLE
[Question] - Fragment SavedStateRegistryOwner

### ISSUE THREAD

**Issue by GuilhE** [elye/demo_android_viewmodel_complete#1]
Hello again Elye.
When creating this logic inside a Fragment:
https://github.com/elye/demo_android_viewmodel_complete/blob/0a74e7645bdd7e33163a4fa0d1c06c7b516f9298/app/src/main/java/com/elyeproj/simpleviewmodel/daggerandroid/MyViewModelAndroidDaggerActivity.kt#L17

the `SavedStateRegistryOwner` should be `this` or `viewLifecycleOwner as SavedStateRegistryOwner`?

Thanks again.

**Comment by elye** [comment]
I believe you can just use `this`, as per the developer of the feature state that Fragment is also implementing `SavedStateRegistryOwner` https://stackoverflow.com/a/57838815/3286489
